### ISSUE TITLE
Availability for .NET Framework

### ISSUE THREAD

**Issue by bigoper** [portyanikhin/SharpProp#114]
## INTRO
- I would like to use `CoolProp` in my project 
- Since `CoolProp` is no longer available as a package, I wish to use `SharpProp` (which looks **amazing** BTW)
- Based on the package dependencies, I can only see `net6.0` and `net7.0`

## QUESTION / ASK
- Is there a plan to have `.Net 4.X` supported at some point?
- Any alternative(s)?

## RESOURCES
<img width="438" alt="image" src="https://user-images.githubusercontent.com/7744385/210908823-62ec38c2-a9ba-4c32-815c-955be9b4e305.png">

Thanks in advance!

**Comment by portyanikhin** [comment]
Hello!

Thank you for your interest in SharpProp!

Until now, I have not thought about the need for support .NET Framework 4.x and other earlier versions of .NET. You mean .NET Framework 4.8?

In any case, I will try to implement it in the near future.

_If you want to speed up the process, you can open a pull request._

Thanks!

**Comment by bigoper** [comment]
Hi @portyanikhin 

Thank you for your prompt response!
- Yes, I was thinking of `.NET 4.8`.
- I'll make sure to submit a **PR**.

Thanks again!
